// <auto-generated />
using HRManager.Data;
using HRManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HRManager.Migrations
{
    [DbContext(typeof(EmployeeContextDB))]
    partial class EmployeeContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HRManager.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<int>("Department");

                    b.Property<string>("Email");

                    b.Property<int>("EmploymentStatus");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("FavoriteColor");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int?>("ManagerEmployeeId");

                    b.Property<string>("PassWord");

                    b.Property<int>("PermissionLevel");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Position");

                    b.Property<int>("Shift");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("UserName");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ManagerEmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HRManager.Models.Employee", b =>
                {
                    b.HasOne("HRManager.Models.Employee", "Manager")
                        .WithMany("Employee_List")
                        .HasForeignKey("ManagerEmployeeId");
                });
#pragma warning restore 612, 618
        }
    }
}
